### ISSUE TITLE
Probably down to the 'greedy' markdown library used but...

### ISSUE THREAD

**Issue by superian** [gromnitsky/dreamwidth-js#10]
`Lorem ipsum dolor sit amet, (*consectetur adipiscing elit*), sed do eiusmod tempor incididunt ut labore et dolore *magna* aliqua. `

..gets translated by entry-post-md to..

`Lorem ipsum dolor sit amet, (<em>consectetur adipiscing elit*), sed do eiusmod tempor incididunt ut labore et dolore *magna</em> aliqua. `

..rather than the expected..

`Lorem ipsum dolor sit amet, (<em>consectetur adipiscing elit</em>), sed do eiusmod tempor incididunt ut labore et dolore <em>magna</em> aliqua. `

Github formats that string as expected:

Lorem ipsum dolor sit amet, (*consectetur adipiscing elit*), sed do eiusmod tempor incididunt ut labore et dolore *magna* aliqua.

**Comment by superian** [comment]
Current workaround is to use a script to call entry-post instead, but with `!markdown` as the first line so that DW formats it as markdown.

**Comment by gromnitsky** [comment]
check 0.4.4 version on npm
