### ISSUE TITLE
Posting markdown

### ISSUE THREAD

**Issue by superian** [gromnitsky/dreamwidth-js#8]
First, huge thanks for this - after a OS update, the long-unsupported drivel client won't install even from my copy of the 3.0.5 .deb, so I am without a DW client.

(Looks at readme) Well, markdown looks the better option, let's try it...

```
---
subject Test post
tags: markdown
security: access
---

Hello markdown posting world
```

```
$dreamwidth-js entry-post-md <test.md 
entry-post-md: YAMLException: end of the stream or a document separator is expected at line 2, column 5:
    tags: markdown
        ^
```
If I install kramdown and use that to convert to HTML..

```
kramdown test.md | dreamwidth-js entry-post
```
.. it posts (yay) but with no subject, tags and as private (oh). I can easily edit those, but what is the secret to posting via markdown?

**Comment by superian** [comment]
Ah, if I copy and paste your markdown example, it works.

I'm not sure what I got wrong with mine, but copying and editing the header-matter works and I can uninstall kramdown / Ruby...

**Comment by gromnitsky** [comment]
you have a typo in:

~~~
---
subject Test post
~~~

`:` after *subject* is missing

**Comment by superian** [comment]
Oops!

Thank you, and thank you again for doing this. I know that DW does not have the popularity of various other social networking sites, but I am really surprised that all of the Linux LJ clients seem to be long dead.

**Comment by gromnitsky** [comment]
You're welcome.

Linux LJ clients are long dead for nobody sane is still using LJ.

Unfortunately, LJ->DW migration was rather limited, people just moved to fb/twitter instead, hence no variety in DW clients.
