### ISSUE TITLE
entry-post-md doesn't do superscript and subscript

### ISSUE THREAD

**Issue by superian** [gromnitsky/dreamwidth-js#9]
```
19^th^

H~2~O
```
.. doesn't superscript the th or subscript the 2 when posted - the ^ are shown instead and, although only one is used either side, ~ is treated as strikeout.

I can see from the preview that github's markdown may not support these, but DW allows the super/subscript HTML.

**Comment by superian** [comment]
19^th^
H~2~O

**Comment by superian** [comment]
Ah, this is something that varies between markdown implementations/specs and we're supposed to use HTML tags to do this.. but if I wanted to use HTML tags, I wouldn't be using markdown!

**Comment by gromnitsky** [comment]
entry-post-md uses a markdown parser called *marked*

it doesn't understand such a syntax:

~~~
$ npm -g i marked
...

$ echo '19^th^ and H~2~O' | marked
<p>19^th^ and H<del>2</del>O</p>
~~~

but pandoc 2.19.2, for example, supports it:

~~~
$ echo '19^th^ and H~2~O' | pandoc
<p>19<sup>th</sup> and H<sub>2</sub>O</p>
~~~

if you don't like *marked*, you can use any external markdown-to-html converter like so:

~~~
echo '19^th^ and H~2~O' | pandoc | \
  dreamwidth-js entry-post -s 'my subject' -t 'markdown,lol' --security public
~~~
